version: '3.0'
services:
  web:
    container_name: php_blogpost
    build: .
    ports:
      - '7000:80'
    volumes:
      - ./app:/var/www/html
    links:
      - db
  db:
    container_name: db_blogpost
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db_blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes:
      - ./database:/var/lib/mysql
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci
    #   - ./database:/var/lib/mysql
    # ./database.sql:/docker-entrypoint-initdb.d/init.sql
